---
- name: install Docker
  hosts: all
  become: docker
  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install docker.io
      ansible.builtin.apt:
        name: "docker.io"
        state: latest
        update_cache: true
